# Generated by Django 4.2.26 on 2025-12-02 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_blogs', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.country')),
            ],
            options={
                'verbose_name': 'Daily Analytics Summary',
                'verbose_name_plural': 'Daily Analytics Summaries',
                'indexes': [models.Index(fields=['date', 'country'], name='analytics_d_date_ebd0b6_idx'), models.Index(fields=['date', 'author'], name='analytics_d_date_b4b394_idx')],
                'unique_together': {('date', 'country', 'author')},
            },
        ),
    ]
